### ISSUE TITLE
Angular 11 error

### ISSUE THREAD

**Issue by var-kar** [jogboms/ngx-numeral#3]
Hi, 

I just found this error on Angular 11.

    Error: node_modules/ngx-numeral/dist/index.d.ts:3:23 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).

    3     static forRoot(): ModuleWithProviders;

Placing a generic type for ModuleWithProviders will fix it. ModuleWithProviders<T>.

Thank you.

**Comment by CormacWhite-rsc** [comment]
I'm getting this error also.

**Comment by jogboms** [comment]
I accept PRs, I quit working in this space a long time now

**Comment by jogboms** [comment]
Closed by #4
